[package]
name = "hc32l13x-ddl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hc32l13x-pac = {path="../hc32l13x-pac"}
num_enum = "0.5.7"
